import { AIPersonalityTrait } from "../types";

export const personalityCategories: { [key: string]: AIPersonalityTrait[] } = {
	"Social Orientation": [
		AIPersonalityTrait.OUTGOING,
		AIPersonalityTrait.RESERVED,
		AIPersonalityTrait.WARM,
		AIPersonalityTrait.GUARDED,
		AIPersonalityTrait.FLIRTATIOUS,
		AIPersonalityTrait.STOIC,
		AIPersonalityTrait.SPONTANEOUS,
		AIPersonalityTrait.METHODICAL,
		AIPersonalityTrait.CHARMING,
		AIPersonalityTrait.ALOOF,
		AIPersonalityTrait.NURTURING,
		AIPersonalityTrait.PLAYFUL,
		AIPersonalityTrait.COMPETITIVE,
		AIPersonalityTrait.COOPERATIVE,
	],
	"Communication Tone": [
		AIPersonalityTrait.TALKATIVE,
		AIPersonalityTrait.CONCISE,
		AIPersonalityTrait.DIRECT,
		AIPersonalityTrait.DIPLOMATIC,
		AIPersonalityTrait.WITTY,
		AIPersonalityTrait.DRY_HUMORED,
		AIPersonalityTrait.FORMAL,
		AIPersonalityTrait.CASUAL,
		AIPersonalityTrait.STORYTELLING,
		AIPersonalityTrait.SARCASTIC,
		AIPersonalityTrait.SUPPORTIVE,
		AIPersonalityTrait.ENCOURAGING,
		AIPersonalityTrait.ASSERTIVE,
		AIPersonalityTrait.REFLECTIVE,
		AIPersonalityTrait.ANIMATED,
		AIPersonalityTrait.MATTER_OF_FACT,
	],
	"Emotional Temperature": [
		AIPersonalityTrait.CHEERFUL,
		AIPersonalityTrait.CALM,
		AIPersonalityTrait.ENTHUSIASTIC,
		AIPersonalityTrait.IRRITABLE,
		AIPersonalityTrait.ANXIOUS,
		AIPersonalityTrait.MELANCHOLIC,
		AIPersonalityTrait.BALANCED,
		AIPersonalityTrait.LIVELY,
		AIPersonalityTrait.MOODY,
		AIPersonalityTrait.SENTIMENTAL,
		AIPersonalityTrait.LIGHT_HEARTED,
		AIPersonalityTrait.SENSITIVE,
		AIPersonalityTrait.SERENE,
	],
	"Motivational Drive & Self-Regulation": [
		AIPersonalityTrait.AMBITIOUS,
		AIPersonalityTrait.LAID_BACK,
		AIPersonalityTrait.GOAL_ORIENTED,
		AIPersonalityTrait.PATIENT,
		AIPersonalityTrait.RESTLESS,
		AIPersonalityTrait.ADAPTIVE,
		AIPersonalityTrait.IMPULSIVE,
		AIPersonalityTrait.PERSISTENT,
		AIPersonalityTrait.DISCIPLINED,
		AIPersonalityTrait.PROCRASTINATING,
		AIPersonalityTrait.OPPORTUNISTIC,
		AIPersonalityTrait.RESILIENT,
		AIPersonalityTrait.DETAIL_DRIVEN,
	],
	"Cognitive Lens": [
		AIPersonalityTrait.ANALYTICAL,
		AIPersonalityTrait.CREATIVE,
		AIPersonalityTrait.LOGICAL,
		AIPersonalityTrait.IMAGINATIVE,
		AIPersonalityTrait.PRACTICAL,
		AIPersonalityTrait.VISIONARY,
		AIPersonalityTrait.CURIOUS,
		AIPersonalityTrait.SKEPTICAL,
		AIPersonalityTrait.DETAIL_ORIENTED,
		AIPersonalityTrait.BIG_PICTURE,
		AIPersonalityTrait.EXPERIMENTAL,
		AIPersonalityTrait.INTUITIVE,
		AIPersonalityTrait.STRUCTURED,
		AIPersonalityTrait.ABSTRACT_MINDED,
	],
	"Outlook / World-View": [
		AIPersonalityTrait.OPTIMISTIC,
		AIPersonalityTrait.REALISTIC,
		AIPersonalityTrait.PESSIMISTIC,
		AIPersonalityTrait.PRAGMATIC,
		AIPersonalityTrait.IDEALISTIC,
		AIPersonalityTrait.GROWTH_MINDED,
		AIPersonalityTrait.TRADITION_MINDED,
		AIPersonalityTrait.EXISTENTIAL,
		AIPersonalityTrait.ROMANTIC,
		AIPersonalityTrait.CYNICAL,
		AIPersonalityTrait.ALTRUISTIC,
		AIPersonalityTrait.CHALLENGING,
		AIPersonalityTrait.COMMUNITY_FOCUSED,
	],
};

export const orderedPersonalityCategories = [
	"Social Orientation",
	"Communication Tone",
	"Emotional Temperature",
	"Motivational Drive & Self-Regulation",
	"Cognitive Lens",
	"Outlook / World-View",
];

export const personalityTraitDescriptions: {
	[key in AIPersonalityTrait]: string;
} = {
	[AIPersonalityTrait.OUTGOING]: "Sociable, enjoys meeting new people.",
	[AIPersonalityTrait.RESERVED]: "Quiet, keeps to themselves.",
	[AIPersonalityTrait.WARM]: "Friendly and approachable.",
	[AIPersonalityTrait.GUARDED]: "Cautious about sharing feelings.",
	[AIPersonalityTrait.FLIRTATIOUS]: "Playfully romantic or teasing.",
	[AIPersonalityTrait.STOIC]: "Unemotional, rarely shows feelings.",
	[AIPersonalityTrait.SPONTANEOUS]: "Acts on impulse, loves surprises.",
	[AIPersonalityTrait.METHODICAL]: "Careful, plans everything out.",
	[AIPersonalityTrait.CHARMING]: "Wins people over easily.",
	[AIPersonalityTrait.ALOOF]: "Distant, hard to get close to.",
	[AIPersonalityTrait.NURTURING]: "Caring, supportive of others.",
	[AIPersonalityTrait.PLAYFUL]: "Lighthearted, loves to joke.",
	[AIPersonalityTrait.COMPETITIVE]: "Driven to win or be the best.",
	[AIPersonalityTrait.COOPERATIVE]: "Works well with others.",

	[AIPersonalityTrait.TALKATIVE]: "Enjoys conversation, chatty.",
	[AIPersonalityTrait.CONCISE]: "Gets to the point quickly.",
	[AIPersonalityTrait.DIRECT]: "Says what they mean, no sugarcoating.",
	[AIPersonalityTrait.DIPLOMATIC]: "Tactful, avoids conflict.",
	[AIPersonalityTrait.WITTY]: "Clever and quick with humor.",
	[AIPersonalityTrait.DRY_HUMORED]: "Subtle, understated sense of humor.",
	[AIPersonalityTrait.FORMAL]: "Polite, uses proper language.",
	[AIPersonalityTrait.CASUAL]: "Relaxed, informal style.",
	[AIPersonalityTrait.STORYTELLING]: "Loves to tell stories.",
	[AIPersonalityTrait.SARCASTIC]: "Uses irony or mockery.",
	[AIPersonalityTrait.SUPPORTIVE]: "Encourages and uplifts others.",
	[AIPersonalityTrait.ENCOURAGING]: "Motivates and inspires.",
	[AIPersonalityTrait.ASSERTIVE]: "Speaks up for themselves.",
	[AIPersonalityTrait.REFLECTIVE]: "Thinks deeply before speaking.",
	[AIPersonalityTrait.ANIMATED]: "Expressive, uses lots of gestures.",
	[AIPersonalityTrait.MATTER_OF_FACT]: "Unemotional, just the facts.",

	[AIPersonalityTrait.CHEERFUL]: "Usually happy and upbeat.",
	[AIPersonalityTrait.CALM]: "Relaxed, not easily upset.",
	[AIPersonalityTrait.ENTHUSIASTIC]: "Eager and energetic.",
	[AIPersonalityTrait.IRRITABLE]: "Easily annoyed or frustrated.",
	[AIPersonalityTrait.ANXIOUS]: "Often worried or nervous.",
	[AIPersonalityTrait.MELANCHOLIC]: "Tends to feel sad or pensive.",
	[AIPersonalityTrait.BALANCED]: "Stable, not easily swayed emotionally.",
	[AIPersonalityTrait.LIVELY]: "Full of energy and spirit.",
	[AIPersonalityTrait.MOODY]: "Emotions change quickly.",
	[AIPersonalityTrait.SENTIMENTAL]: "Easily moved by feelings or memories.",
	[AIPersonalityTrait.LIGHT_HEARTED]: "Takes things lightly, not serious.",
	[AIPersonalityTrait.SENSITIVE]: "Easily affected by others’ feelings.",
	[AIPersonalityTrait.SERENE]: "Peaceful and untroubled.",

	[AIPersonalityTrait.AMBITIOUS]: "Sets high goals, strives to achieve.",
	[AIPersonalityTrait.LAID_BACK]: "Easygoing, not easily stressed.",
	[AIPersonalityTrait.GOAL_ORIENTED]: "Focused on achieving objectives.",
	[AIPersonalityTrait.PATIENT]: "Willing to wait, not easily frustrated.",
	[AIPersonalityTrait.RESTLESS]: "Always needs to be doing something.",
	[AIPersonalityTrait.ADAPTIVE]: "Adjusts easily to change.",
	[AIPersonalityTrait.IMPULSIVE]: "Acts without thinking.",
	[AIPersonalityTrait.PERSISTENT]: "Keeps going, doesn’t give up.",
	[AIPersonalityTrait.DISCIPLINED]: "Self-controlled and organized.",
	[AIPersonalityTrait.PROCRASTINATING]: "Puts things off until later.",
	[AIPersonalityTrait.OPPORTUNISTIC]: "Takes advantage of situations.",
	[AIPersonalityTrait.RESILIENT]: "Bounces back from setbacks.",
	[AIPersonalityTrait.DETAIL_DRIVEN]: "Pays close attention to details.",

	[AIPersonalityTrait.ANALYTICAL]: "Breaks things down logically.",
	[AIPersonalityTrait.CREATIVE]: "Thinks outside the box.",
	[AIPersonalityTrait.LOGICAL]: "Uses reason and clear thinking.",
	[AIPersonalityTrait.IMAGINATIVE]: "Has a vivid, creative mind.",
	[AIPersonalityTrait.PRACTICAL]: "Prefers realistic solutions.",
	[AIPersonalityTrait.VISIONARY]: "Sees big possibilities for the future.",
	[AIPersonalityTrait.CURIOUS]: "Eager to learn and explore.",
	[AIPersonalityTrait.SKEPTICAL]: "Questions things, not easily convinced.",
	[AIPersonalityTrait.DETAIL_ORIENTED]: "Notices small things others miss.",
	[AIPersonalityTrait.BIG_PICTURE]: "Focuses on overall goals.",
	[AIPersonalityTrait.EXPERIMENTAL]: "Likes to try new things.",
	[AIPersonalityTrait.INTUITIVE]: "Trusts gut feelings.",
	[AIPersonalityTrait.STRUCTURED]: "Prefers order and routines.",
	[AIPersonalityTrait.ABSTRACT_MINDED]: "Thinks in concepts and ideas.",

	[AIPersonalityTrait.OPTIMISTIC]: "Expects the best to happen.",
	[AIPersonalityTrait.REALISTIC]: "Sees things as they are.",
	[AIPersonalityTrait.PESSIMISTIC]: "Expects the worst to happen.",
	[AIPersonalityTrait.PRAGMATIC]: "Practical, focuses on results.",
	[AIPersonalityTrait.IDEALISTIC]: "Guided by high ideals and values.",
	[AIPersonalityTrait.GROWTH_MINDED]: "Believes in self-improvement.",
	[AIPersonalityTrait.TRADITION_MINDED]: "Values customs and traditions.",
	[AIPersonalityTrait.EXISTENTIAL]: "Thinks about life’s big questions.",
	[AIPersonalityTrait.ROMANTIC]: "Sees the world with love and passion.",
	[AIPersonalityTrait.CYNICAL]: "Distrusts motives of others.",
	[AIPersonalityTrait.ALTRUISTIC]: "Puts others’ needs first.",
	[AIPersonalityTrait.CHALLENGING]: "Pushes boundaries and questions norms.",
	[AIPersonalityTrait.COMMUNITY_FOCUSED]: "Cares about the greater good.",

	[AIPersonalityTrait.CONFIDENT]: "Self-assured and bold.",
	[AIPersonalityTrait.SHY]: "Reserved, avoids attention.",
	[AIPersonalityTrait.EMPATHETIC]: "Understands and shares others’ feelings.",
	[AIPersonalityTrait.HUMBLE]: "Modest, not boastful.",
	[AIPersonalityTrait.INTROVERTED]: "Prefers solitude or small groups.",
	[AIPersonalityTrait.EXTROVERTED]: "Energized by social interaction.",
	[AIPersonalityTrait.SAD]: "Often feels down or unhappy.",
	[AIPersonalityTrait.GRUMPY]: "Frequently irritable or cranky.",
	[AIPersonalityTrait.SERIOUS]: "Grave, not playful or joking.",
};
