import { AIPersonalityTrait } from "../types";

export const personalityCategories: { [key: string]: AIPersonalityTrait[] } = {
	"Social Orientation": [
		AIPersonalityTrait.OUTGOING,
		AIPersonalityTrait.RESERVED,
		AIPersonalityTrait.WARM,
		AIPersonalityTrait.GUARDED,
		AIPersonalityTrait.FLIRTATIOUS,
		AIPersonalityTrait.STOIC,
		AIPersonalityTrait.SPONTANEOUS,
		AIPersonalityTrait.METHODICAL,
		AIPersonalityTrait.CHARMING,
		AIPersonalityTrait.ALOOF,
		AIPersonalityTrait.NURTURING,
		AIPersonalityTrait.PLAYFUL,
		AIPersonalityTrait.COMPETITIVE,
		AIPersonalityTrait.COOPERATIVE,
	],
	"Communication Tone": [
		AIPersonalityTrait.TALKATIVE,
		AIPersonalityTrait.CONCISE,
		AIPersonalityTrait.DIRECT,
		AIPersonalityTrait.DIPLOMATIC,
		AIPersonalityTrait.WITTY,
		AIPersonalityTrait.DRY_HUMORED,
		AIPersonalityTrait.FORMAL,
		AIPersonalityTrait.CASUAL,
		AIPersonalityTrait.STORYTELLING,
		AIPersonalityTrait.SARCASTIC,
		AIPersonalityTrait.SUPPORTIVE,
		AIPersonalityTrait.ENCOURAGING,
		AIPersonalityTrait.ASSERTIVE,
		AIPersonalityTrait.REFLECTIVE,
		AIPersonalityTrait.ANIMATED,
		AIPersonalityTrait.MATTER_OF_FACT,
	],
	"Emotional Temperature": [
		AIPersonalityTrait.CHEERFUL,
		AIPersonalityTrait.CALM,
		AIPersonalityTrait.ENTHUSIASTIC,
		AIPersonalityTrait.IRRITABLE,
		AIPersonalityTrait.ANXIOUS,
		AIPersonalityTrait.MELANCHOLIC,
		AIPersonalityTrait.BALANCED,
		AIPersonalityTrait.LIVELY,
		AIPersonalityTrait.MOODY,
		AIPersonalityTrait.SENTIMENTAL,
		AIPersonalityTrait.LIGHT_HEARTED,
		AIPersonalityTrait.SENSITIVE,
		AIPersonalityTrait.SERENE,
	],
	"Motivational Drive & Self-Regulation": [
		AIPersonalityTrait.AMBITIOUS,
		AIPersonalityTrait.LAID_BACK,
		AIPersonalityTrait.GOAL_ORIENTED,
		AIPersonalityTrait.PATIENT,
		AIPersonalityTrait.RESTLESS,
		AIPersonalityTrait.ADAPTIVE,
		AIPersonalityTrait.IMPULSIVE,
		AIPersonalityTrait.PERSISTENT,
		AIPersonalityTrait.DISCIPLINED,
		AIPersonalityTrait.PROCRASTINATING,
		AIPersonalityTrait.OPPORTUNISTIC,
		AIPersonalityTrait.RESILIENT,
		AIPersonalityTrait.DETAIL_DRIVEN,
	],
	"Cognitive Lens": [
		AIPersonalityTrait.ANALYTICAL,
		AIPersonalityTrait.CREATIVE,
		AIPersonalityTrait.LOGICAL,
		AIPersonalityTrait.IMAGINATIVE,
		AIPersonalityTrait.PRACTICAL,
		AIPersonalityTrait.VISIONARY,
		AIPersonalityTrait.CURIOUS,
		AIPersonalityTrait.SKEPTICAL,
		AIPersonalityTrait.DETAIL_ORIENTED,
		AIPersonalityTrait.BIG_PICTURE,
		AIPersonalityTrait.EXPERIMENTAL,
		AIPersonalityTrait.INTUITIVE,
		AIPersonalityTrait.STRUCTURED,
		AIPersonalityTrait.ABSTRACT_MINDED,
	],
	"Outlook / World-View": [
		AIPersonalityTrait.OPTIMISTIC,
		AIPersonalityTrait.REALISTIC,
		AIPersonalityTrait.PESSIMISTIC,
		AIPersonalityTrait.PRAGMATIC,
		AIPersonalityTrait.IDEALISTIC,
		AIPersonalityTrait.GROWTH_MINDED,
		AIPersonalityTrait.TRADITION_MINDED,
		AIPersonalityTrait.EXISTENTIAL,
		AIPersonalityTrait.ROMANTIC,
		AIPersonalityTrait.CYNICAL,
		AIPersonalityTrait.ALTRUISTIC,
		AIPersonalityTrait.CHALLENGING,
		AIPersonalityTrait.COMMUNITY_FOCUSED,
	],
};

export const orderedPersonalityCategories = [
	"Social Orientation",
	"Communication Tone",
	"Emotional Temperature",
	"Motivational Drive & Self-Regulation",
	"Cognitive Lens",
	"Outlook / World-View",
];

export const personalityTraitDescriptions: {
	[key in AIPersonalityTrait]: string;
} = {
	[AIPersonalityTrait.OUTGOING]: "Sociable, enjoys meeting new people.",
	[AIPersonalityTrait.RESERVED]: "Quiet, keeps to themselves.",
	[AIPersonalityTrait.WARM]: "Friendly and approachable.",
	[AIPersonalityTrait.GUARDED]: "Cautious about sharing feelings.",
	[AIPersonalityTrait.FLIRTATIOUS]: "Playfully romantic or teasing.",
	[AIPersonalityTrait.STOIC]: "Unemotional, rarely shows feelings.",
	[AIPersonalityTrait.SPONTANEOUS]: "Acts on impulse, loves surprises.",
	[AIPersonalityTrait.METHODICAL]: "Careful, plans everything out.",
	[AIPersonalityTrait.CHARMING]: "Wins people over easily.",
	[AIPersonalityTrait.ALOOF]: "Distant, hard to get close to.",
	[AIPersonalityTrait.NURTURING]: "Caring, supportive of others.",
	[AIPersonalityTrait.PLAYFUL]: "Lighthearted, loves to joke.",
	[AIPersonalityTrait.COMPETITIVE]: "Driven to win or be the best.",
	[AIPersonalityTrait.COOPERATIVE]: "Works well with others.",

	[AIPersonalityTrait.TALKATIVE]: "Enjoys conversation, chatty.",
	[AIPersonalityTrait.CONCISE]: "Gets to the point quickly.",
	[AIPersonalityTrait.DIRECT]: "Says what they mean, no sugarcoating.",
	[AIPersonalityTrait.DIPLOMATIC]: "Tactful, avoids conflict.",
	[AIPersonalityTrait.WITTY]: "Clever and quick with humor.",
	[AIPersonalityTrait.DRY_HUMORED]: "Subtle, understated sense of humor.",
	[AIPersonalityTrait.FORMAL]: "Polite, uses proper language.",
	[AIPersonalityTrait.CASUAL]: "Relaxed, informal style.",
	[AIPersonalityTrait.STORYTELLING]: "Loves to tell stories.",
	[AIPersonalityTrait.SARCASTIC]: "Uses irony or mockery.",
	[AIPersonalityTrait.SUPPORTIVE]: "Encourages and uplifts others.",
	[AIPersonalityTrait.ENCOURAGING]: "Motivates and inspires.",
	[AIPersonalityTrait.ASSERTIVE]: "Speaks up for themselves.",
	[AIPersonalityTrait.REFLECTIVE]: "Thinks deeply before speaking.",
	[AIPersonalityTrait.ANIMATED]: "Expressive, uses lots of gestures.",
	[AIPersonalityTrait.MATTER_OF_FACT]: "Unemotional, just the facts.",

	[AIPersonalityTrait.CHEERFUL]: "Usually happy and upbeat.",
	[AIPersonalityTrait.CALM]: "Relaxed, not easily upset.",
	[AIPersonalityTrait.ENTHUSIASTIC]: "Eager and energetic.",
	[AIPersonalityTrait.IRRITABLE]: "Easily annoyed or frustrated.",
	[AIPersonalityTrait.ANXIOUS]: "Often worried or nervous.",
	[AIPersonalityTrait.MELANCHOLIC]: "Tends to feel sad or pensive.",
	[AIPersonalityTrait.BALANCED]: "Stable, not easily swayed emotionally.",
	[AIPersonalityTrait.LIVELY]: "Full of energy and spirit.",
	[AIPersonalityTrait.MOODY]: "Emotions change quickly.",
	[AIPersonalityTrait.SENTIMENTAL]: "Easily moved by feelings or memories.",
	[AIPersonalityTrait.LIGHT_HEARTED]: "Takes things lightly, not serious.",
	[AIPersonalityTrait.SENSITIVE]: "Easily affected by others’ feelings.",
	[AIPersonalityTrait.SERENE]: "Peaceful and untroubled.",

	[AIPersonalityTrait.AMBITIOUS]: "Sets high goals, strives to achieve.",
	[AIPersonalityTrait.LAID_BACK]: "Easygoing, not easily stressed.",
	[AIPersonalityTrait.GOAL_ORIENTED]: "Focused on achieving objectives.",
	[AIPersonalityTrait.PATIENT]: "Willing to wait, not easily frustrated.",
	[AIPersonalityTrait.RESTLESS]: "Always needs to be doing something.",
	[AIPersonalityTrait.ADAPTIVE]: "Adjusts easily to change.",
	[AIPersonalityTrait.IMPULSIVE]: "Acts without thinking.",
	[AIPersonalityTrait.PERSISTENT]: "Keeps going, doesn’t give up.",
	[AIPersonalityTrait.DISCIPLINED]: "Self-controlled and organized.",
	[AIPersonalityTrait.PROCRASTINATING]: "Puts things off until later.",
	[AIPersonalityTrait.OPPORTUNISTIC]: "Takes advantage of situations.",
	[AIPersonalityTrait.RESILIENT]: "Bounces back from setbacks.",
	[AIPersonalityTrait.DETAIL_DRIVEN]: "Pays close attention to details.",

	[AIPersonalityTrait.ANALYTICAL]: "Breaks things down logically.",
	[AIPersonalityTrait.CREATIVE]: "Thinks outside the box.",
	[AIPersonalityTrait.LOGICAL]: "Uses reason and clear thinking.",
	[AIPersonalityTrait.IMAGINATIVE]: "Has a vivid, creative mind.",
	[AIPersonalityTrait.PRACTICAL]: "Prefers realistic solutions.",
	[AIPersonalityTrait.VISIONARY]: "Sees big possibilities for the future.",
	[AIPersonalityTrait.CURIOUS]: "Eager to learn and explore.",
	[AIPersonalityTrait.SKEPTICAL]: "Questions things, not easily convinced.",
	[AIPersonalityTrait.DETAIL_ORIENTED]: "Notices small things others miss.",
	[AIPersonalityTrait.BIG_PICTURE]: "Focuses on overall goals.",
	[AIPersonalityTrait.EXPERIMENTAL]: "Likes to try new things.",
	[AIPersonalityTrait.INTUITIVE]: "Trusts gut feelings.",
	[AIPersonalityTrait.STRUCTURED]: "Prefers order and routines.",
	[AIPersonalityTrait.ABSTRACT_MINDED]: "Thinks in concepts and ideas.",

	[AIPersonalityTrait.OPTIMISTIC]: "Expects the best to happen.",
	[AIPersonalityTrait.REALISTIC]: "Sees things as they are.",
	[AIPersonalityTrait.PESSIMISTIC]: "Expects the worst to happen.",
	[AIPersonalityTrait.PRAGMATIC]: "Practical, focuses on results.",
	[AIPersonalityTrait.IDEALISTIC]: "Guided by high ideals and values.",
	[AIPersonalityTrait.GROWTH_MINDED]: "Believes in self-improvement.",
	[AIPersonalityTrait.TRADITION_MINDED]: "Values customs and traditions.",
	[AIPersonalityTrait.EXISTENTIAL]: "Thinks about life’s big questions.",
	[AIPersonalityTrait.ROMANTIC]: "Sees the world with love and passion.",
	[AIPersonalityTrait.CYNICAL]: "Distrusts motives of others.",
	[AIPersonalityTrait.ALTRUISTIC]: "Puts others’ needs first.",
	[AIPersonalityTrait.CHALLENGING]: "Pushes boundaries and questions norms.",
	[AIPersonalityTrait.COMMUNITY_FOCUSED]: "Cares about the greater good.",

	[AIPersonalityTrait.CONFIDENT]: "Self-assured and bold.",
	[AIPersonalityTrait.SHY]: "Reserved, avoids attention.",
	[AIPersonalityTrait.EMPATHETIC]: "Understands and shares others’ feelings.",
	[AIPersonalityTrait.HUMBLE]: "Modest, not boastful.",
	[AIPersonalityTrait.INTROVERTED]: "Prefers solitude or small groups.",
	[AIPersonalityTrait.EXTROVERTED]: "Energized by social interaction.",
	[AIPersonalityTrait.SAD]: "Often feels down or unhappy.",
	[AIPersonalityTrait.GRUMPY]: "Frequently irritable or cranky.",
	[AIPersonalityTrait.SERIOUS]: "Grave, not playful or joking.",
};

// --- Culture/Gender-Aware Name Data ---
// This structure can be expanded as needed for more cultures and names.
export const cultureNameData: {
	[culture: string]: {
		male: string[];
		female: string[];
		neutral: string[];
		last: string[];
	};
} = {
	Japanese: {
		male: ["Haruto", "Yuto", "Sota", "Ren", "Kaito"],
		female: ["Yui", "Aoi", "Sakura", "Hina", "Rin"],
		neutral: ["Haru", "Akira", "Kaoru", "Makoto", "Nao"],
		last: ["Sato", "Suzuki", "Takahashi", "Tanaka", "Watanabe"],
	},
	"Italian-American": {
		male: ["Giovanni", "Antonio", "Luca", "Marco", "Vincenzo"],
		female: ["Giulia", "Francesca", "Alessia", "Martina", "Chiara"],
		neutral: ["Andrea", "Gabriele", "Sam", "Alex", "Morgan"],
		last: ["Russo", "Romano", "Esposito", "Bianchi", "Ferraro"],
	},
	Nigerian: {
		male: ["Chinedu", "Emeka", "Ifeanyi", "Tunde", "Babatunde"],
		female: ["Ngozi", "Chiamaka", "Amara", "Adaeze", "Yetunde"],
		neutral: ["Chika", "Uche", "Ife", "Tola", "Femi"],
		last: ["Okafor", "Adebayo", "Eze", "Ogunleye", "Nwosu"],
	},
	French: {
		male: ["Louis", "Hugo", "Gabriel", "Arthur", "Jules"],
		female: ["Emma", "Louise", "Chloé", "Camille", "Léa"],
		neutral: ["Alex", "Charlie", "Sacha", "Noa", "Morgan"],
		last: ["Martin", "Bernard", "Dubois", "Thomas", "Robert"],
	},
	German: {
		male: ["Lukas", "Leon", "Finn", "Paul", "Jonas"],
		female: ["Mia", "Emma", "Hannah", "Sophia", "Anna"],
		neutral: ["Alex", "Robin", "Sascha", "Kim", "Jules"],
		last: ["Müller", "Schmidt", "Schneider", "Fischer", "Weber"],
	},
	British: {
		male: ["Oliver", "George", "Harry", "Jack", "Charlie"],
		female: ["Olivia", "Amelia", "Isla", "Emily", "Ava"],
		neutral: ["Alex", "Morgan", "Taylor", "Casey", "Sam"],
		last: ["Smith", "Jones", "Taylor", "Brown", "Williams"],
	},
	Irish: {
		male: ["Conor", "Sean", "Cian", "Oisin", "Patrick"],
		female: ["Aoife", "Saoirse", "Ciara", "Niamh", "Emma"],
		neutral: ["Rory", "Casey", "Morgan", "Alex", "Shay"],
		last: ["Murphy", "Kelly", "O’Sullivan", "Walsh", "Byrne"],
	},
	Scottish: {
		male: ["Lewis", "Jack", "Finlay", "Callum", "Euan"],
		female: ["Emily", "Sophie", "Isla", "Ava", "Ellie"],
		neutral: ["Cameron", "Alex", "Morgan", "Taylor", "Jamie"],
		last: ["Smith", "Brown", "Wilson", "Stewart", "Campbell"],
	},
	Dutch: {
		male: ["Daan", "Sem", "Luuk", "Bram", "Milan"],
		female: ["Emma", "Tess", "Julia", "Sophie", "Anna"],
		neutral: ["Robin", "Sam", "Alex", "Noa", "Jesse"],
		last: ["de Jong", "Jansen", "de Vries", "van den Berg", "Bakker"],
	},
	Scandinavian: {
		male: ["Lars", "Erik", "Anders", "Johan", "Mats"],
		female: ["Anna", "Emma", "Sara", "Maja", "Ingrid"],
		neutral: ["Alex", "Robin", "Kim", "Sascha", "Noa"],
		last: ["Andersen", "Johansen", "Larsen", "Nielsen", "Olsen"],
	},
	Norwegian: {
		male: ["Ola", "Magnus", "Kristian", "Anders", "Marius"],
		female: ["Nora", "Emma", "Sara", "Ingrid", "Julie"],
		neutral: ["Alex", "Robin", "Kim", "Sascha", "Noa"],
		last: ["Hansen", "Johansen", "Olsen", "Larsen", "Andersen"],
	},
	Swedish: {
		male: ["Erik", "Johan", "Karl", "Lars", "Anders"],
		female: ["Anna", "Emma", "Elsa", "Sara", "Maja"],
		neutral: ["Alex", "Robin", "Kim", "Sascha", "Noa"],
		last: ["Johansson", "Andersson", "Karlsson", "Nilsson", "Eriksson"],
	},
	Danish: {
		male: ["Mads", "Frederik", "Emil", "Magnus", "Oliver"],
		female: ["Ida", "Emma", "Sofie", "Freja", "Anna"],
		neutral: ["Alex", "Robin", "Kim", "Sascha", "Noa"],
		last: ["Jensen", "Nielsen", "Hansen", "Pedersen", "Andersen"],
	},
	Polish: {
		male: ["Jakub", "Kacper", "Szymon", "Jan", "Filip"],
		female: ["Zuzanna", "Julia", "Maja", "Hanna", "Aleksandra"],
		neutral: ["Alex", "Patryk", "Dominik", "Kuba", "Ola"],
		last: ["Nowak", "Kowalski", "Wiśniewski", "Wójcik", "Kowalczyk"],
	},
	Russian: {
		male: ["Ivan", "Dmitry", "Alexei", "Sergey", "Nikolai"],
		female: ["Anna", "Maria", "Olga", "Elena", "Tatiana"],
		neutral: ["Sasha", "Valery", "Alex", "Nikita", "Vanya"],
		last: ["Ivanov", "Petrov", "Sidorov", "Smirnov", "Volkov"],
	},
	Greek: {
		male: ["Giorgos", "Dimitris", "Nikos", "Kostas", "Vasilis"],
		female: ["Maria", "Eleni", "Katerina", "Vasiliki", "Sofia"],
		neutral: ["Alex", "Niki", "Chris", "Danae", "Nikos"],
		last: ["Papadopoulos", "Vasileiou", "Nikolaidis", "Georgiou", "Pappas"],
	},
	Swiss: {
		male: ["Luca", "Noah", "Leon", "Elias", "Julian"],
		female: ["Mia", "Lea", "Lina", "Sofia", "Anna"],
		neutral: ["Alex", "Robin", "Kim", "Sascha", "Noa"],
		last: ["Müller", "Meier", "Schmid", "Keller", "Weber"],
	},
	Austrian: {
		male: ["Lukas", "David", "Tobias", "Florian", "Paul"],
		female: ["Anna", "Laura", "Sarah", "Julia", "Lena"],
		neutral: ["Alex", "Robin", "Kim", "Sascha", "Noa"],
		last: ["Gruber", "Huber", "Bauer", "Wagner", "Müller"],
	},
	Belgian: {
		male: ["Lucas", "Louis", "Arthur", "Noah", "Jules"],
		female: ["Emma", "Louise", "Mila", "Elise", "Alice"],
		neutral: ["Alex", "Robin", "Kim", "Sascha", "Noa"],
		last: ["Peeters", "Janssens", "Maes", "Jacobs", "Mertens"],
	},
	Portuguese: {
		male: ["João", "Francisco", "Afonso", "Tomás", "Martim"],
		female: ["Maria", "Matilde", "Leonor", "Carolina", "Beatriz"],
		neutral: ["Alex", "Rafa", "Dani", "Noa", "Sam"],
		last: ["Silva", "Santos", "Ferreira", "Pereira", "Oliveira"],
	},
	Canadian: {
		male: ["Liam", "Noah", "Jackson", "Lucas", "Benjamin"],
		female: ["Emma", "Olivia", "Charlotte", "Sophia", "Amelia"],
		neutral: ["Alex", "Taylor", "Morgan", "Casey", "Jordan"],
		last: ["Smith", "Brown", "Tremblay", "Martin", "Roy"],
	},
	Australian: {
		male: ["Jack", "William", "Noah", "Thomas", "James"],
		female: ["Charlotte", "Olivia", "Amelia", "Isla", "Mia"],
		neutral: ["Alex", "Taylor", "Morgan", "Casey", "Jordan"],
		last: ["Smith", "Jones", "Williams", "Brown", "Wilson"],
	},
	NewZealander: {
		male: ["Oliver", "Jack", "Noah", "William", "James"],
		female: ["Charlotte", "Isla", "Olivia", "Amelia", "Emily"],
		neutral: ["Alex", "Taylor", "Morgan", "Casey", "Jordan"],
		last: ["Smith", "Williams", "Brown", "Taylor", "Wilson"],
	},
	American: {
		male: ["James", "John", "Robert", "Michael", "William"],
		female: ["Mary", "Patricia", "Jennifer", "Linda", "Elizabeth"],
		neutral: ["Alex", "Taylor", "Jordan", "Morgan", "Casey"],
		last: ["Smith", "Johnson", "Williams", "Brown", "Jones"],
	},
	Spanish: {
		male: ["Mateo", "Santiago", "Alejandro", "Diego", "Adrián"],
		female: ["Lucía", "Sofía", "Martina", "Paula", "Valeria"],
		neutral: ["Alex", "Cruz", "Noa", "Ariel", "Sam"],
		last: ["García", "Martínez", "López", "Sánchez", "Pérez"],
	},
	Chinese: {
		male: ["Wei", "Jie", "Lei", "Ming", "Jun"],
		female: ["Li", "Mei", "Xiu", "Fang", "Yan"],
		neutral: ["Yu", "Qing", "An", "Lin", "Rong"],
		last: ["Wang", "Li", "Zhang", "Liu", "Chen"],
	},
};
